name: Release miunlock

on:
  push:
    paths:
      - MiUnlockTool.py
  pull_request:
    paths:
      - MiUnlockTool.py
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          version=$(grep -oP '(?<=version = ")(.*)(?=")' MiUnlockTool.py)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: tag
        run: |
          if ! git tag | grep -q "$VERSION"; then
            git tag "$VERSION"
            git push origin "$VERSION"
          fi

      - name: release
        run: |
          if ! gh release view $VERSION; then
            gh release create $VERSION --title "Release $VERSION" --notes "VERSION: $VERSION"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}

      - name: upload
        run: |
          gh release edit $VERSION --notes "VERSION: $VERSION"
          gh release upload $VERSION ./MiUnlockTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}