name: Release miunlock

on:
  push:
    paths:
      - MiUnlockTool.py
  pull_request:
    paths:
      - MiUnlockTool.py
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          version=$(grep -oP '(?<=version = ")(.*)(?=")' MiUnlockTool.py)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: add miunlock version and upload file
        run: |
          gh release edit miunlock --notes "VERSION: $VERSION"
          gh release upload miunlock ./MiUnlockTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}