name: Release miunlock

on:
  push:
    paths:
      - MiUnlockTool.py
  pull_request:
    paths:
      - MiUnlockTool.py
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          version=$(grep -oP '(?<=version = ")(.*)(?=")' MiUnlockTool.py)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag | grep -q "$VERSION"; then
            echo "Tag $VERSION already exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag $VERSION does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create tag if not exists
        if: env.TAG_EXISTS == 'false'
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Add miunlock version and upload file
        run: |
          gh release edit $VERSION --notes "VERSION: $VERSION"
          gh release upload $VERSION ./MiUnlockTool.py --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}